// <auto-generated/> — Manual implementation based on DiamondOnlineFileFormats.md
#nullable enable

namespace MartialHeroes.Serialization.DO;

/// <summary>Delegate for parsing a single DO record from a fixed-size byte span.</summary>
/// <typeparam name="T">The record type to produce.</typeparam>
/// <param name="data">Raw record bytes (exactly <c>recordSize</c> bytes).</param>
/// <returns>A parsed record instance.</returns>
public delegate T DoRecordParser<out T>(ReadOnlySpan<byte> data);

/// <summary>
///     Reads Diamond Object (.do) binary files — headerless flat arrays of fixed-size records.
/// </summary>
/// <remarks>
///     DO files have no header. Record count is determined by <c>fileSize / recordSize</c>.
///     This is identical to the SCR loading pattern used throughout the Diamond Engine.
/// </remarks>
public static class DoReader
{
    /// <summary>
    ///     Reads all records from a headerless DO file.
    /// </summary>
    /// <param name="data">Raw file bytes.</param>
    /// <param name="recordSize">Size of each record in bytes.</param>
    /// <param name="parser">Delegate that parses a single record from a byte span.</param>
    /// <typeparam name="T">Record type.</typeparam>
    /// <returns>Array of parsed records.</returns>
    /// <exception cref="ArgumentException">
    ///     Thrown when <paramref name="data"/> length is not evenly divisible by <paramref name="recordSize"/>.
    /// </exception>
    public static T[] ReadAll<T>(ReadOnlySpan<byte> data, int recordSize, DoRecordParser<T> parser)
    {
        if (data.Length % recordSize != 0)
            throw new ArgumentException(
                $"File size ({data.Length} bytes) is not evenly divisible by record size ({recordSize} bytes).",
                nameof(data));

        var count = data.Length / recordSize;
        var records = new T[count];

        for (var i = 0; i < count; i++)
        {
            var slice = data.Slice(i * recordSize, recordSize);
            records[i] = parser(slice);
        }

        return records;
    }

    /// <summary>
    ///     Reads all records from a headerless DO file and builds a dictionary indexed by key.
    /// </summary>
    /// <param name="data">Raw file bytes.</param>
    /// <param name="recordSize">Size of each record in bytes.</param>
    /// <param name="parser">Delegate that parses a single record from a byte span.</param>
    /// <param name="keySelector">Function to extract the dictionary key from a parsed record.</param>
    /// <typeparam name="TKey">Key type (must implement <see cref="object.GetHashCode"/>).</typeparam>
    /// <typeparam name="T">Record type.</typeparam>
    /// <returns>Dictionary mapping keys to records. Duplicate keys are overwritten (last wins).</returns>
    public static Dictionary<TKey, T> ReadAllIndexed<TKey, T>(
        ReadOnlySpan<byte> data,
        int recordSize,
        DoRecordParser<T> parser,
        Func<T, TKey> keySelector) where TKey : notnull
    {
        var records = ReadAll(data, recordSize, parser);
        var dict = new Dictionary<TKey, T>(records.Length);

        foreach (var record in records)
            dict[keySelector(record)] = record;

        return dict;
    }

    /// <summary>
    ///     Reads all complete records, silently discarding any trailing bytes that do not form a complete record.
    ///     Use this variant for DO files whose size is not an exact multiple of <paramref name="recordSize" />
    ///     (e.g. *ma.do class-skill-tree files which contain MSVC debug uninitialized-memory padding at the end).
    /// </summary>
    /// <param name="data">Raw file bytes.</param>
    /// <param name="recordSize">Size of each record in bytes.</param>
    /// <param name="parser">Delegate that parses a single record from a byte span.</param>
    /// <typeparam name="T">Record type.</typeparam>
    /// <returns>Array of all complete records; trailing partial bytes are ignored.</returns>
    public static T[] ReadAllTruncating<T>(ReadOnlySpan<byte> data, int recordSize, DoRecordParser<T> parser)
    {
        var count = data.Length / recordSize;
        var records = new T[count];

        for (var i = 0; i < count; i++)
            records[i] = parser(data.Slice(i * recordSize, recordSize));

        return records;
    }
}
