// <auto-generated/> — Manual implementation based on DiamondOnlineFileFormats.md
#nullable enable

namespace MartialHeroes.Serialization.DO;

/// <summary>Delegate for writing a single DO record into a fixed-size byte span.</summary>
/// <typeparam name="T">The record type to serialize.</typeparam>
/// <param name="record">The record to write.</param>
/// <param name="destination">
///     Target span (exactly <c>recordSize</c> bytes). Callers should clear the span before invoking.
/// </param>
public delegate void DoRecordWriter<in T>(T record, Span<byte> destination);

/// <summary>
///     Writes Diamond Object (.do) binary files — headerless flat arrays of fixed-size records.
/// </summary>
/// <remarks>
///     DO files have no header. The output is simply N consecutive records of fixed size.
/// </remarks>
public static class DoWriter
{
    /// <summary>
    ///     Writes all records to a byte array with no header.
    /// </summary>
    /// <param name="records">Records to write.</param>
    /// <param name="recordSize">Size of each record in bytes.</param>
    /// <param name="writer">Delegate that writes a single record into a byte span.</param>
    /// <typeparam name="T">Record type.</typeparam>
    /// <returns>Byte array containing the serialized records.</returns>
    public static byte[] WriteAll<T>(IReadOnlyList<T> records, int recordSize, DoRecordWriter<T> writer)
    {
        var buffer = new byte[records.Count * recordSize];

        for (var i = 0; i < records.Count; i++)
        {
            var slice = buffer.AsSpan(i * recordSize, recordSize);
            writer(records[i], slice);
        }

        return buffer;
    }
}
